/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicio3;

import javax.swing.JOptionPane;

/**
 *
 * @author silas
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        salarioTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        aumentoTextField = new javax.swing.JTextField();
        assTecRadioButton = new javax.swing.JRadioButton();
        assAdminRadioButton = new javax.swing.JRadioButton();
        aplicarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        turnoComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        adicionalNoturnoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bonusTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        matriculaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Salario:");

        jLabel3.setText("Aumento:");

        buttonGroup1.add(assTecRadioButton);
        assTecRadioButton.setText("Assistente Tecnico");
        assTecRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assTecRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(assAdminRadioButton);
        assAdminRadioButton.setText("Assistente Administrativo");
        assAdminRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assAdminRadioButtonActionPerformed(evt);
            }
        });

        aplicarButton.setText("Aplicar");
        aplicarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Turno:");

        turnoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno" }));
        turnoComboBox.setEnabled(false);

        jLabel5.setText("Adicional Noturno:");

        adicionalNoturnoTextField.setEnabled(false);

        jLabel6.setText("Bonus:");

        bonusTextField.setEnabled(false);

        jLabel7.setText("Matricula:");

        matriculaTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assTecRadioButton)
                    .addComponent(turnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(aplicarButton)
                    .addComponent(jLabel6)
                    .addComponent(bonusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(assAdminRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(matriculaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adicionalNoturnoTextField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(aumentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assTecRadioButton)
                    .addComponent(assAdminRadioButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aumentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionalNoturnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(aplicarButton)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarButtonActionPerformed
        
        if(assTecRadioButton.isSelected()) {
              
            AssistenteTec assTec = new AssistenteTec("", 0.0, 0, 0.0, 0);
            
            assTec.setNome(nameTextField.getText());
            assTec.setSalario(Double.parseDouble(salarioTextField.getText()));
            assTec.setAumento(Integer.parseInt(aumentoTextField.getText()));
            assTec.setBonus(Double.parseDouble(bonusTextField.getText()));
            assTec.setMatricula(Integer.parseInt(matriculaTextField.getText()));
            
            JOptionPane.showMessageDialog(null, assTec.toString());
            
        } else if(assAdminRadioButton.isSelected()) {
        
            AssistenteAdmin assAdm = new AssistenteAdmin("", 0.0, 0, "", 0.0);
            
            assAdm.setNome(nameTextField.getText());
            assAdm.setSalario(Double.parseDouble(salarioTextField.getText()));
            assAdm.setAumento(Integer.parseInt(aumentoTextField.getText()));
            assAdm.setTurno(turnoComboBox.getSelectedItem().toString());
            assAdm.setAdicionalNot(Double.parseDouble(adicionalNoturnoTextField.getText()));
            
            JOptionPane.showMessageDialog(null, assAdm.toString());
            
        } else {

            Funcionario func = new Funcionario("", 0.0, 0);

            func.setNome(nameTextField.getText());
            func.setSalario(Double.parseDouble(salarioTextField.getText()));
            func.setAumento(Integer.parseInt(aumentoTextField.getText()));

            JOptionPane.showMessageDialog(null, func.toString());
        
        }
    }//GEN-LAST:event_aplicarButtonActionPerformed

    private void assTecRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assTecRadioButtonActionPerformed

        bonusTextField.setEnabled(true);
        matriculaTextField.setEnabled(true);
        turnoComboBox.setEnabled(false);
        adicionalNoturnoTextField.setEnabled(false);
        
    }//GEN-LAST:event_assTecRadioButtonActionPerformed

    private void assAdminRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assAdminRadioButtonActionPerformed
            
        bonusTextField.setEnabled(false);
        matriculaTextField.setEnabled(false);
        turnoComboBox.setEnabled(true);
        adicionalNoturnoTextField.setEnabled(true);
    }//GEN-LAST:event_assAdminRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adicionalNoturnoTextField;
    private javax.swing.JButton aplicarButton;
    private javax.swing.JRadioButton assAdminRadioButton;
    private javax.swing.JRadioButton assTecRadioButton;
    private javax.swing.JTextField aumentoTextField;
    private javax.swing.JTextField bonusTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField salarioTextField;
    private javax.swing.JComboBox<String> turnoComboBox;
    // End of variables declaration//GEN-END:variables
}
