/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicio2;

import javax.swing.JOptionPane;

/**
 *
 * @author silas
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        super("Jogos");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        classifcText = new javax.swing.JTextField();
        descText = new javax.swing.JTextField();
        precoText = new javax.swing.JTextField();
        aplicarButton = new javax.swing.JButton();
        jogosRadioButton = new javax.swing.JRadioButton();
        jgDigitaisRadioButton = new javax.swing.JRadioButton();
        jgFisicosRadioButton = new javax.swing.JRadioButton();
        consoleRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        platafornaTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tamanhoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        marcaTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tempoEntregaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Classificação:");

        jLabel3.setText("Desconto:");

        jLabel4.setText("Preço:");

        nameText.setEnabled(false);

        classifcText.setEnabled(false);

        descText.setEnabled(false);

        precoText.setEnabled(false);

        aplicarButton.setText("Aplicar");
        aplicarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jogosRadioButton);
        jogosRadioButton.setText("Jogos");
        jogosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogosRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jgDigitaisRadioButton);
        jgDigitaisRadioButton.setText("Jogos digitais");
        jgDigitaisRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgDigitaisRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jgFisicosRadioButton);
        jgFisicosRadioButton.setText("Jogos fisicos");
        jgFisicosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgFisicosRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(consoleRadioButton);
        consoleRadioButton.setText("Console");
        consoleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleRadioButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Plataforma:");

        platafornaTextField.setEnabled(false);

        jLabel6.setText("Tamanho (GB):");

        tamanhoTextField.setEnabled(false);

        jLabel7.setText("Marca:");

        marcaTextField.setEnabled(false);

        jLabel8.setText("Tempo Entrega (dias)");

        tempoEntregaTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classifcText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoText)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(platafornaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tamanhoTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marcaTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempoEntregaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jogosRadioButton)
                        .addGap(48, 48, 48)
                        .addComponent(jgDigitaisRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jgFisicosRadioButton)
                        .addGap(41, 41, 41)
                        .addComponent(consoleRadioButton)
                        .addGap(29, 29, 29)
                        .addComponent(aplicarButton)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(platafornaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(classifcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tamanhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(descText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(marcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tempoEntregaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(consoleRadioButton)
                        .addComponent(aplicarButton)
                        .addComponent(jgFisicosRadioButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jogosRadioButton)
                        .addComponent(jgDigitaisRadioButton)))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarButtonActionPerformed

        if(jgDigitaisRadioButton.isSelected()){
            
            JogoDigital jgDig = new JogoDigital("" ,0, 0, 0, "", 0);
        
            jgDig.setNome(nameText.getText());
            jgDig.setClassificacao(Integer.parseInt(classifcText.getText()));
            jgDig.setDesconto(Double.parseDouble(descText.getText()));
            jgDig.setPreco(Double.parseDouble(precoText.getText()));
            jgDig.setPlataforma(platafornaTextField.getText());
            jgDig.setTamanhoDow(Double.parseDouble(tamanhoTextField.getText()));

            JOptionPane.showMessageDialog(null, jgDig.toString());
            
            
        } else if(jgFisicosRadioButton.isSelected()){
            
            JogoFisico jgFisc = new JogoFisico("" ,0, 0, 0, 0);
        
            jgFisc.setNome(nameText.getText());
            jgFisc.setClassificacao(Integer.parseInt(classifcText.getText()));
            jgFisc.setDesconto(Double.parseDouble(descText.getText()));
            jgFisc.setPreco(Double.parseDouble(precoText.getText()));
            jgFisc.setTempoEntrega(Integer.parseInt(tempoEntregaTextField.getText()));

            JOptionPane.showMessageDialog(null, jgFisc.toString());
            
            
        } else if(consoleRadioButton.isSelected()){
            
            Console cons = new Console("", 0, 0, 0, "", 0);
        
            cons.setNome(nameText.getText());
            cons.setClassificacao(Integer.parseInt(classifcText.getText()));
            cons.setDesconto(Double.parseDouble(descText.getText()));
            cons.setPreco(Double.parseDouble(precoText.getText()));
            cons.setMarca(marcaTextField.getText());
            cons.setTamanhoGB(Double.parseDouble(tamanhoTextField.getText()));
            cons.setMarca(marcaTextField.getText());
            
            JOptionPane.showMessageDialog(null, cons.toString());
            
            
        } else {
            
            Jogos jogo = new Jogos("", 0, 0, 0);
        
            jogo.setNome(nameText.getText());
            jogo.setClassificacao(Integer.parseInt(classifcText.getText()));
            jogo.setDesconto(Double.parseDouble(descText.getText()));
            jogo.setPreco(Double.parseDouble(precoText.getText()));

            JOptionPane.showMessageDialog(null, jogo.toString());
        }
        
        nameText.setText("");
        classifcText.setText("");
        descText.setText("");
        precoText.setText("");
        platafornaTextField.setText("");
        tamanhoTextField.setText("");
        marcaTextField.setText("");
        tempoEntregaTextField.setText("");
        
    }//GEN-LAST:event_aplicarButtonActionPerformed

    private void jogosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogosRadioButtonActionPerformed
        
        nameText.setEnabled(true);
        classifcText.setEnabled(true);
        descText.setEnabled(true);
        precoText.setEnabled(true);
        tempoEntregaTextField.setEnabled(false);
        platafornaTextField.setEnabled(false);
        tamanhoTextField.setEnabled(false);
        marcaTextField.setEnabled(false);
        
    }//GEN-LAST:event_jogosRadioButtonActionPerformed

    private void jgDigitaisRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgDigitaisRadioButtonActionPerformed
        descText.setText("15");
        nameText.setEnabled(true);
        classifcText.setEnabled(true);
        descText.setEnabled(false);
        precoText.setEnabled(true);
        tempoEntregaTextField.setEnabled(false);
        platafornaTextField.setEnabled(true);
        tamanhoTextField.setEnabled(true);
        marcaTextField.setEnabled(false);
        
    }//GEN-LAST:event_jgDigitaisRadioButtonActionPerformed

    private void jgFisicosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgFisicosRadioButtonActionPerformed
        nameText.setEnabled(true);
        classifcText.setEnabled(true);
        descText.setEnabled(true);
        precoText.setEnabled(true);
        tempoEntregaTextField.setEnabled(true);
        platafornaTextField.setEnabled(false);
        tamanhoTextField.setEnabled(false);
        marcaTextField.setEnabled(false);
    }//GEN-LAST:event_jgFisicosRadioButtonActionPerformed

    private void consoleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleRadioButtonActionPerformed
        descText.setText("10");
        nameText.setEnabled(true);
        classifcText.setEnabled(true);
        descText.setEnabled(false);
        precoText.setEnabled(true);
        platafornaTextField.setEnabled(false);
        tamanhoTextField.setEnabled(true);
        marcaTextField.setEnabled(true);
    }//GEN-LAST:event_consoleRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField classifcText;
    private javax.swing.JRadioButton consoleRadioButton;
    private javax.swing.JTextField descText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jgDigitaisRadioButton;
    private javax.swing.JRadioButton jgFisicosRadioButton;
    private javax.swing.JRadioButton jogosRadioButton;
    private javax.swing.JTextField marcaTextField;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField platafornaTextField;
    private javax.swing.JTextField precoText;
    private javax.swing.JTextField tamanhoTextField;
    private javax.swing.JTextField tempoEntregaTextField;
    // End of variables declaration//GEN-END:variables
}
